import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetServerSideProps, GetStaticProps } from 'next';

export default function Home({ repositories, date }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>          
        </h1>
        <h3>
          Updated: {date}
        </h3>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {
            repositories.map((repo) => (
              <a 
                key={repo.name}
                href={repo.url}
                className={styles.card}
                target="_blank"                
              >
                <h2>{repo.name} &rarr;</h2>
                <p>{repo.description}</p>
                <div className={styles.language}>
                  Language: {repo.language}
                </div>
              </a>     
            ))
          }
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
// export const getServerSideProps: GetServerSideProps = async() => {
//   const url = 'https://api.github.com/users/Andersonlimahw/repos';
//   const response = await fetch(url);
//   const data = await response.json();
//   console.log('## Data: ', data);
//   const repositoriesMapped = data.map((repo) => ({
//     name: repo.name,
//     url: repo.html_url, 
//     description: repo.description, 
//     owner: {
//       name: repo.owner.login,
//       avatarUrl: repo.owner.avatar_url
//     }
//   }));

//   return {
//     props: {
//       repositories: repositoriesMapped, 
//       date: new Date().toISOString()
//     }
//   }
// }

export const getStaticProps: GetStaticProps = async() => {
  const url = 'https://api.github.com/users/Andersonlimahw/repos';
  const response = await fetch(url);
  const data = await response.json();
  console.log('## Data: ', data);
  const repositoriesMapped = data.map((repo) => ({
    name: repo.name,
    url: repo.html_url, 
    description: repo.description, 
    language: repo.language,
    owner: {
      name: repo.owner.login,
      avatarUrl: repo.owner.avatar_url
    }
  }));

  return {
    props: {
      repositories: repositoriesMapped, 
      date: new Date().toUTCString()
    }, 
    revalidate: 5
  }
}
